// 무기 코드 → 화면에 쓸 이름.
//
// 숙련도 응답은 `Item_Weapon_M24_C` 꼴로 온다. 접두사만 벗기면 `BerylM762`처럼 실제로
// 부르지 않는 이름이 남는다(다들 "Beryl"이라고 한다). 그 손질을 여기서 한다.
//
// 한글로 바꾸지 않는다. M24·AKM·Kar98k는 한국 유저도 그대로 부르고, 억지로 옮기면
// 오히려 못 알아본다. 줄여 부르는 것만 줄인다.
//
// 여기 없는 코드는 접두사만 벗긴 이름이 그대로 나온다 — 새 무기가 추가돼도 깨지지 않는다.
export const WEAPON_ALIAS: Record<string, string> = {
  Item_Weapon_ACE32_C: "ACE32",
  Item_Weapon_AK47_C: "AK47",
  Item_Weapon_AUG_C: "AUG",
  Item_Weapon_AWM_C: "AWM",
  Item_Weapon_Berreta686_C: "Berreta686",
  Item_Weapon_BerylM762_C: "BerylM762",
  Item_Weapon_BizonPP19_C: "BizonPP19",
  Item_Weapon_BluezoneGrenade_C: "BluezoneGrenade",
  Item_Weapon_C4_C: "C4",
  Item_Weapon_Crossbow_C: "Crossbow",
  Item_Weapon_DP12_C: "DP12",
  Item_Weapon_DP28_C: "DP28",
  Item_Weapon_DesertEagle_C: "DesertEagle",
  Item_Weapon_Dragunov_C: "Dragunov",
  Item_Weapon_FAMASG2_C: "FAMASG2",
  Item_Weapon_FNFal_C: "FNFal",
  Item_Weapon_G18_C: "G18",
  Item_Weapon_G36C_C: "G36C",
  Item_Weapon_Grenade_C: "Grenade",
  Item_Weapon_Groza_C: "Groza",
  Item_Weapon_HK416_C: "HK416",
  Item_Weapon_JS9_C: "JS9",
  Item_Weapon_K2_C: "K2",
  Item_Weapon_Kar98k_C: "Kar98k",
  Item_Weapon_L6_C: "L6",
  Item_Weapon_M16A4_C: "M16A4",
  Item_Weapon_M1911_C: "M1911",
  Item_Weapon_M249_C: "M249",
  Item_Weapon_M24_C: "M24",
  Item_Weapon_M9_C: "M9",
  Item_Weapon_MG3_C: "MG3",
  Item_Weapon_MP5K_C: "MP5K",
  Item_Weapon_MP9_C: "MP9",
  Item_Weapon_Mini14_C: "Mini14",
  Item_Weapon_Mk12_C: "Mk12",
  Item_Weapon_Mk14_C: "Mk14",
  Item_Weapon_Mk47Mutant_C: "Mk47Mutant",
  Item_Weapon_Molotov_C: "Molotov",
  Item_Weapon_Mortar_C: "Mortar",
  Item_Weapon_Mosin_C: "Mosin",
  Item_Weapon_NagantM1895_C: "NagantM1895",
  Item_Weapon_P90_C: "P90",
  Item_Weapon_PanzerFaust100M_C: "PanzerFaust100M",
  Item_Weapon_QBU88_C: "QBU88",
  Item_Weapon_QBZ95_C: "QBZ95",
  Item_Weapon_RPD_C: "RPD",
  "Item_Weapon_SCAR-L_C": "SCAR-L",
  Item_Weapon_SKS_C: "SKS",
  Item_Weapon_Saiga12_C: "Saiga12",
  Item_Weapon_Sawnoff_C: "Sawnoff",
  Item_Weapon_StickyGrenade_C: "StickyGrenade",
  Item_Weapon_Thompson_C: "Thompson",
  Item_Weapon_UMP_C: "UMP",
  Item_Weapon_UZI_C: "UZI",
  Item_Weapon_VSS_C: "VSS",
  Item_Weapon_Vector_C: "Vector",
  Item_Weapon_Win1894_C: "Win1894",
  Item_Weapon_Winchester_C: "Winchester",
  Item_Weapon_vz61Skorpion_C: "vz61Skorpion",
};
